export { HomePage } from "./home/home";
export { SlidesPage } from './slides/slides'
export { TabsPage } from './tabs/tabs';
export { TodosPage } from './todos/todos';
export { AboutPage } from './about/about'
export { MetalCategoriaPage } from './metal-categoria/metal-categoria';
export { RockCategoriaPage } from './rock-categoria/rock-categoria';
export { MetalPage } from './metal/metal';
export { MetalAlbumPage } from './metal-album/metal-album';